// @ts-nocheck
import {createClient} from "npm:@supabase/supabase-js@2.117.2";import {detectStockTransition} from "../_shared/transition.ts";import {TelegramProvider,restockMessage} from "../_shared/telegram.ts";
const cors={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, x-client-info, apikey, content-type, x-cron-secret"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json"}});
function distance(a:any,b:any){const r=6371000,dLat=(b.latitude-a.latitude)*Math.PI/180,dLon=(b.longitude-a.longitude)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.latitude*Math.PI/180)*Math.cos(b.latitude*Math.PI/180)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
function clusters(stores:any[]){const out:any[][]=[];for(const store of stores){const found=out.find(c=>distance(c[0],store)<=800);if(found)found.push(store);else out.push([store]);}return out;}
async function inventory(itemCode:string,lat:number,lng:number){const url=new URL("/api/gs25/inventory",Deno.env.get("DAISO_API_BASE_URL")??"https://mcp.aka.page");url.searchParams.set("itemCode",itemCode);url.searchParams.set("lat",String(lat));url.searchParams.set("lng",String(lng));url.searchParams.set("storeLimit","50");let last;for(let i=0;i<3;i++){try{const r=await fetch(url,{signal:AbortSignal.timeout(10000)});if(!r.ok){if((r.status===429||r.status>=500)&&i<2){await new Promise(x=>setTimeout(x,300*2**i));continue;}throw new Error(`GS25 ${r.status}`)}const j=await r.json();if(j?.success!==true||!Array.isArray(j?.data?.inventory?.stores))throw new Error("Invalid GS25 response");return j.data.inventory.stores;}catch(e){last=e;if(i<2)await new Promise(x=>setTimeout(x,300*2**i));}}throw last;}
async function runOwner(db:any,ownerId:string,source:"cron"|"manual"){
 const {data:settings}=await db.from("app_settings").select("*").eq("owner_id",ownerId).single();if(!settings?.monitoring_enabled&&source==="cron")return{skipped:true};
 const {data:run,error:runError}=await db.from("check_runs").insert({owner_id:ownerId,source,status:"running"}).select("id").single();if(runError)throw runError;
 try{const {data:targets,error}=await db.from("watch_targets").select("product_id,store_id,products!inner(id,item_code,item_name,enabled,archived_at),stores!inner(id,store_code,store_name,address,latitude,longitude,enabled,archived_at)").eq("owner_id",ownerId).eq("enabled",true).is("archived_at",null).eq("products.enabled",true).is("products.archived_at",null).eq("stores.enabled",true).is("stores.archived_at",null);if(error)throw error;
 const byProduct=new Map();for(const t of targets??[]){const p=t.products,s=t.stores;if(!byProduct.has(p.id))byProduct.set(p.id,{product:p,stores:[]});byProduct.get(p.id).stores.push(s)}let requestCount=0;for(const x of byProduct.values())requestCount+=clusters(x.stores).length;if(requestCount>(settings?.max_requests_per_run??12))throw new Error(`요청 수 ${requestCount}회가 실행 한도보다 큽니다.`);
 const {data:statuses}=await db.from("stock_status").select("product_id,store_id,quantity").eq("owner_id",ownerId);const previous=new Map((statuses??[]).map((s:any)=>[`${s.product_id}:${s.store_id}`,s.quantity]));const {data:destinations}=await db.from("notification_targets").select("id,type,target_identifier").eq("owner_id",ownerId).eq("enabled",true).is("archived_at",null);let checked=0;
 for(const {product,stores} of byProduct.values())for(const group of clusters(stores)){const rows=await inventory(product.item_code,group[0].latitude,group[0].longitude);const rowMap=new Map(rows.map((r:any)=>[r.storeCode,r]));for(const store of group){const row:any=rowMap.get(store.store_code);if(!row)continue;checked++;const now=new Date().toISOString(),current=row.realStockQuantity,key=`${product.id}:${store.id}`,before=previous.has(key)?previous.get(key):null,transition=detectStockTransition(before,current,settings?.initial_notification_enabled??false);await db.from("stock_status").upsert({owner_id:ownerId,product_id:product.id,store_id:store.id,quantity:current,pickup_quantity:row.pickupStockQuantity,delivery_quantity:row.deliveryStockQuantity,is_sold_out:current===0,checked_at:now},{onConflict:"product_id,store_id"});if(transition){const {data:event}=await db.from("stock_events").insert({owner_id:ownerId,product_id:product.id,store_id:store.id,previous_quantity:before,current_quantity:current,event_type:transition.eventType}).select("id").single();if(transition.shouldNotify&&event){let sent=0;for(const d of destinations??[]){if(d.type!=="telegram")continue;try{const token=Deno.env.get("TELEGRAM_BOT_TOKEN");if(!token)throw new Error("TELEGRAM_BOT_TOKEN missing");await new TelegramProvider(token).send(restockMessage(product.item_name,store.store_name,current,store.address,now),d.target_identifier);await db.from("notification_deliveries").insert({owner_id:ownerId,stock_event_id:event.id,notification_target_id:d.id,status:"sent",attempt_count:1,sent_at:now});sent++;}catch(e){await db.from("notification_deliveries").insert({owner_id:ownerId,stock_event_id:event.id,notification_target_id:d.id,status:"failed",attempt_count:1,last_error:String(e)});}}if(sent>0)await db.from("stock_events").update({notified:true,notified_at:now}).eq("id",event.id);}}previous.set(key,current);}}
 await db.from("app_settings").update({next_check_at:new Date(Date.now()+(settings?.check_interval_minutes??10)*60000).toISOString()}).eq("owner_id",ownerId);await db.from("check_runs").update({status:"succeeded",finished_at:new Date().toISOString(),products_checked:byProduct.size,stores_checked:checked,requests_made:requestCount}).eq("id",run.id);return{runId:run.id,products:byProduct.size,stores:checked,requests:requestCount};
 }catch(e){await db.from("check_runs").update({status:"failed",finished_at:new Date().toISOString(),error_message:String(e)}).eq("id",run.id);throw e;}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);const url=Deno.env.get("SUPABASE_URL")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,db=createClient(url,service,{auth:{persistSession:false}});try{const cron=req.headers.get("x-cron-secret"),expected=Deno.env.get("CRON_SECRET");let owners:string[]=[];if(cron&&expected&&cron===expected){const {data}=await db.from("app_settings").select("owner_id").eq("monitoring_enabled",true).lte("next_check_at",new Date().toISOString());owners=(data??[]).map((x:any)=>x.owner_id);}else{const token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token)return json({error:"Unauthorized"},401);const auth=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const {data,error}=await auth.auth.getUser(token);if(error||!data.user)return json({error:"Unauthorized"},401);owners=[data.user.id];}const results=[];for(const owner of owners)results.push(await runOwner(db,owner,cron?"cron":"manual"));return json({ok:true,results});}catch(e){return json({error:e instanceof Error?e.message:"Check failed"},500);}});
